# Generated by Django 5.0.4 on 2024-05-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True)),
                ('item', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('category', models.CharField(choices=[('meal', 'meal'), ('stationary', 'stationary'), ('other', 'other')], max_length=20)),
                ('owner', models.IntegerField()),
            ],
        ),
    ]
